//
//  MMLoopIcon.m
//  LooseLeaf
//
//  Created by Adam Wulf on 3/23/15.
//  Copyright (c) 2015 Milestone Made, LLC. All rights reserved.
//

#import "MMLoopIcon.h"


@implementation MMLoopIcon

- (id)initWithFrame:(CGRect)frame {
    if (self = [super initWithFrame:frame]) {
        self.opaque = NO;
        self.backgroundColor = [UIColor clearColor];
    }
    return self;
}

- (void)drawRect:(CGRect)frame {
    UIBezierPath* loopPath = UIBezierPath.bezierPath;
    [loopPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.13516 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25623 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.10690 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45551 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.10937 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34445 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.10690 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45551 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.19671 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28298 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.10690 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45551 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.16717 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37598 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.20955 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13154 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.20873 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24515 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.22099 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13853 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.13516 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25623 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.19865 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12367 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.15679 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.18222 * CGRectGetHeight(frame))];
    [loopPath closePath];
    [loopPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.28789 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40197 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.33632 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47169 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.30772 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41928 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.33500 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44735 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.33197 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38930 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.34657 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44734 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.35366 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40966 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.28789 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40197 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.31423 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37264 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.29792 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38885 * CGRectGetHeight(frame))];
    [loopPath closePath];
    [loopPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.47737 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41082 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.43837 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48937 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.45917 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42619 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.44212 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45341 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.43719 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52118 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.43768 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49601 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.43725 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51312 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.46717 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47437 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.44830 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50970 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.45964 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48701 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.47737 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41082 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.47886 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45474 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.47908 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42862 * CGRectGetHeight(frame))];
    [loopPath closePath];
    [loopPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.79386 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49918 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.75076 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50642 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.78784 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50043 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.76997 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50145 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.71410 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53344 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.72700 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51256 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.70457 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52925 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.76537 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52734 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.72369 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53608 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.75180 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53220 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.79386 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49918 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.78909 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52224 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.79727 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50993 * CGRectGetHeight(frame))];
    [loopPath closePath];
    [loopPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.27277 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42909 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.25473 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55653 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.25177 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47868 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.24881 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54339 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.25842 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55477 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.25586 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55608 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.25710 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55549 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.30393 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47871 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.27570 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53284 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.30140 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50954 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.27277 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42909 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.30646 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44791 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.28615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43640 * CGRectGetHeight(frame))];
    [loopPath closePath];
    [loopPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.23510 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10680 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.24760 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.22154 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.25040 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13012 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.25289 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.16822 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.20095 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38914 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.24131 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28487 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.22004 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34892 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.10780 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50589 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.13961 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51536 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.10780 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50589 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.10834 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52593 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.10780 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50589 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.10776 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51393 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.13961 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62895 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.10991 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55822 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.11600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61917 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.21762 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58115 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.15972 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63728 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.19431 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60602 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.22506 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57303 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.22026 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57834 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.22275 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57561 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.20929 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49658 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.21995 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56053 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.20857 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52885 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.24274 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38486 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.21019 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45664 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.22331 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41452 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.30017 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34512 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.25872 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36048 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.27896 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34452 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.38195 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44610 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.33444 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34615 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.38195 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38558 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.33652 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58493 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.38423 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50605 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.33652 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58493 * CGRectGetHeight(frame))];
    [loopPath addLineToPoint:CGPointMake(CGRectGetMinX(frame) + 0.40467 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54707 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.40013 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49027 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.40467 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54707 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.39827 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52120 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.49100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35775 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.40126 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47134 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.41153 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35919 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.57279 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48396 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.56444 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35645 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.57279 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48396 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.61317 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41876 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.57279 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48396 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.59273 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45347 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.63870 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34255 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.63048 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38938 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.63356 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36689 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.63785 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32693 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.63819 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33331 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.63785 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32693 * CGRectGetHeight(frame))];
    [loopPath addLineToPoint:CGPointMake(CGRectGetMinX(frame) + 0.67647 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33640 * CGRectGetHeight(frame))];
    [loopPath addLineToPoint:CGPointMake(CGRectGetMinX(frame) + 0.67874 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38872 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.73321 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32555 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.67874 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38872 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.69696 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33961 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.75196 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32183 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.73900 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32330 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.74525 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32195 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.81172 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36701 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.77800 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32138 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.80453 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35634 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.83448 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45090 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.83917 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40775 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.83448 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45090 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.85555 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45168 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.83448 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45090 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.84251 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45322 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.89822 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43987 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.86914 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45008 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.88600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44452 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.93889 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40039 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.91592 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43313 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.93237 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41096 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.95454 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39360 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.94574 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39175 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.94637 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39513 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.95837 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41110 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.95996 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39259 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.96205 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40042 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.89206 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48286 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.94659 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45037 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.91422 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47080 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.83047 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49444 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.87465 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49228 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.83309 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49437 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.77846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56673 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.83007 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49445 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.82521 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56100 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.69410 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54422 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.74898 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57035 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.70027 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56847 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.71829 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47882 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.68510 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50890 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.70514 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48753 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.79964 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45382 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.74203 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46493 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.79964 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45382 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.76291 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36110 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.79964 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45382 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.79504 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35930 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.71080 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42045 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.73922 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36242 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.72519 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38434 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.68101 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50862 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.69394 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46273 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.68101 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50862 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.67808 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69900 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.68101 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50862 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.68308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59958 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.65079 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88109 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.67469 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76652 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.66553 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83649 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.61513 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92829 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.64123 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91002 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.62933 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92827 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.56042 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81934 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.59855 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92830 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.56297 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89921 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.56061 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79576 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.56018 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81192 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.56023 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80407 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.64284 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48252 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.56588 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67556 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.63712 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50314 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.64466 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46445 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.64533 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47354 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.64466 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46445 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.64426 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45491 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.64466 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46445 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.64450 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46058 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.49100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62911 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.60943 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51397 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.53579 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62911 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.42285 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59124 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.43648 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62911 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.42285 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59124 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.31607 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63226 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.42285 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59124 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.35196 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63226 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.25927 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61649 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.28654 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63226 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.25927 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61649 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.25512 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61154 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.25927 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61649 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.25764 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61454 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.16460 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67313 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.23801 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62970 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.19402 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67313 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.07175 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50851 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.14698 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67313 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.08552 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65088 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.05557 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50825 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.07147 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50571 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.06123 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50920 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.04970 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49944 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.05046 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50740 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.04988 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50213 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.05055 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49672 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.04965 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49874 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.04997 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49781 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.06959 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47021 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.05438 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48951 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.06979 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47512 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.06918 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43016 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.06903 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45609 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.06883 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44632 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.09257 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24715 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.07056 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36520 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.07884 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30132 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.11082 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.18932 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.09787 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.22627 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.10398 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20682 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.23510 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10680 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.15324 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.07361 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.20746 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.07036 * CGRectGetHeight(frame))];
    [loopPath closePath];
    [loopPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.50659 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39661 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.51001 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48686 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.51230 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41684 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.52107 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45241 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.44655 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57467 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.50020 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51740 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.46997 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55156 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.46402 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59204 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.45068 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58426 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.45638 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59085 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.52752 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52097 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.48981 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59574 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.52091 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55185 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.52001 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39999 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.53789 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48315 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.54069 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41671 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.50659 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39661 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.51697 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39772 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.51089 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39661 * CGRectGetHeight(frame))];
    [loopPath closePath];
    [loopPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.64080 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61572 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.60232 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76914 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.64080 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61572 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.61086 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70685 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.59939 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86617 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.59580 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81670 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.59574 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85297 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.60360 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87150 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.60049 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87012 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.60192 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87201 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.63381 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75796 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.61145 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86778 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.62694 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81843 * CGRectGetHeight(frame))];
    [loopPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.64080 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61572 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.64072 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69703 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.64080 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61572 * CGRectGetHeight(frame))];
    [loopPath closePath];


    UIColor* darkColor = [[UIColor blackColor] colorWithAlphaComponent:.8];
    [darkColor setFill];
    [loopPath fill];


    CGContextRef context = UIGraphicsGetCurrentContext();

    CGContextSaveGState(context);
    CGContextRestoreGState(context);
}


@end
