//
//  UIBezierPath+MMEmoji.m
//  LooseLeaf
//
//  Created by Adam Wulf on 8/8/18.
//  Copyright © 2018 Milestone Made, LLC. All rights reserved.
//

#import "UIBezierPath+MMEmoji.h"
#import "Constants.h"


@implementation UIBezierPath (MMEmoji)

+ (UIBezierPath*)emojiFacePathForSize:(CGSize)size {
    CGRect frame = CGRectFromSize(size);
    UIBezierPath* facePath = [UIBezierPath bezierPathWithOvalInRect:CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.04600 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.03600 - 0.5) + 1, floor(CGRectGetWidth(frame) * 0.96200 + 0.5) - floor(CGRectGetWidth(frame) * 0.04600 + 0.5), floor(CGRectGetHeight(frame) * 0.95200 - 0.5) - floor(CGRectGetHeight(frame) * 0.03600 - 0.5))];
    return facePath;
}

+ (UIBezierPath*)emojiJoyPathForSize:(CGSize)size {
    CGRect frame = CGRectFromSize(size);
    UIBezierPath* joyPath = [UIBezierPath bezierPath];
    [joyPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49505 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.94748 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60989 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53471 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.95696 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57319 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.97499 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64267 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.95859 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62079 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.96819 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63191 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.95964 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76937 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 1.00980 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69778 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.98929 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74364 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.86693 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77445 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.94059 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78591 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.89950 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79033 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.50400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95305 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.78318 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88307 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.65176 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95305 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.13985 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77286 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.35552 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95305 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.22354 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88239 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.04049 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77139 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.10644 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79291 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.06087 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78907 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.02515 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64468 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.01085 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74566 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + -0.00967 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69980 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.05940 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60548 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.03329 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63180 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.04545 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61839 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49505 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.05065 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57011 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53312 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.23652 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12323 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34195 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.12112 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20639 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.50400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03705 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.31177 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06900 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.40415 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03705 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49505 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.75695 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03705 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24210 * CGRectGetHeight(frame))];
    [joyPath closePath];
    return joyPath;
}

+ (UIBezierPath*)emojiPrayPathForSize:(CGSize)size {
    CGRect frame = CGRectFromSize(size);
    UIBezierPath* prayPath = [UIBezierPath bezierPath];
    [prayPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.61658 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11817 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.64069 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31795 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.62416 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20142 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.62921 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28582 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.66354 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37212 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.65217 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35008 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.65861 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35229 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.69670 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54687 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.66752 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38816 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.68245 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48602 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.70653 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58221 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.70007 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56123 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.70340 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57353 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.77933 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68503 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.72296 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62764 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.77078 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67861 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.80345 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68964 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.78787 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69145 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.79581 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68842 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(500.5, 396.57) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.80931 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69058 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(470.28, 380.36)];
    [prayPath addCurveToPoint:CGPointMake(500.5, 495.5) controlPoint1:CGPointMake(500.5, 454.72) controlPoint2:CGPointMake(500.5, 495.5)];
    [prayPath addLineToPoint:CGPointMake(CGRectGetMinX(frame) + 0.66432 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99100 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.60072 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89387 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.64893 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96809 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.60849 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90771 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.58633 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84555 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.59108 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87670 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.60258 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86145 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.53226 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81274 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.58032 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83968 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.55107 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82684 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.51462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79093 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.52094 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80426 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.51629 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79077 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.49599 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81370 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.51244 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79113 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.50817 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80457 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.44130 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84856 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.47597 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82871 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.44472 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84301 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.43263 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89401 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.43082 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86559 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.44227 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87684 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.36616 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99100 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.42486 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90785 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.38237 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96812 * CGRectGetHeight(frame))];
    [prayPath addLineToPoint:CGPointMake(CGRectGetMinX(frame) + 0.00100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99100 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.00100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81228 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.00100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99100 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.00100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91829 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.22672 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69364 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.02206 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80095 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.21949 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69480 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.25084 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68703 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.23435 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69242 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.24229 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69345 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.32363 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58221 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.25938 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68061 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.30721 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62764 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.36863 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37212 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.34005 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53678 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.36370 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39195 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.39347 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31795 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.37355 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35229 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.38199 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35008 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.41758 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11817 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.40496 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28582 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.41000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20142 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.42161 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08212 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.41878 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10497 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.42010 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09297 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.46203 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00100 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.42860 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03173 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.43966 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00620 * CGRectGetHeight(frame))];
    [prayPath addLineToPoint:CGPointMake(CGRectGetMinX(frame) + 0.48210 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00100 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.51708 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03679 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.50035 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00457 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.51239 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.01743 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.54806 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00100 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.52177 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.01743 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.52981 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00457 * CGRectGetHeight(frame))];
    [prayPath addLineToPoint:CGPointMake(CGRectGetMinX(frame) + 0.56826 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00100 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.61658 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11817 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.59611 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00733 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.60980 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04367 * CGRectGetHeight(frame))];
    [prayPath closePath];
    return prayPath;
}


@end
