//
//  UIBezierPath+MMEmoji.m
//  LooseLeaf
//
//  Created by Adam Wulf on 8/8/18.
//  Copyright © 2018 Milestone Made, LLC. All rights reserved.
//

#import "UIBezierPath+MMEmoji.h"
#import "Constants.h"


@implementation UIBezierPath (MMEmoji)

+ (UIBezierPath*)emojiFacePathForSize:(CGSize)size {
    CGRect frame = CGRectFromSize(size);
    UIBezierPath* facePath = [UIBezierPath bezierPathWithOvalInRect:CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.04600 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.03600 - 0.5) + 1, floor(CGRectGetWidth(frame) * 0.96200 + 0.5) - floor(CGRectGetWidth(frame) * 0.04600 + 0.5), floor(CGRectGetHeight(frame) * 0.95200 - 0.5) - floor(CGRectGetHeight(frame) * 0.03600 - 0.5))];
    return facePath;
}

+ (UIBezierPath*)emojiJoyPathForSize:(CGSize)size {
    CGRect frame = CGRectFromSize(size);
    UIBezierPath* joyPath = [UIBezierPath bezierPath];
    [joyPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49505 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.94748 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60989 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53471 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.95696 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57319 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.97499 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64267 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.95859 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62079 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.96819 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63191 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.95964 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76937 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 1.00980 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69778 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.98929 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74364 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.86693 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77445 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.94059 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78591 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.89950 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79033 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.50400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95305 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.78318 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88307 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.65176 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95305 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.13985 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77286 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.35552 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95305 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.22354 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88239 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.04049 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77139 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.10644 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79291 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.06087 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78907 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.02515 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64468 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.01085 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74566 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + -0.00967 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69980 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.05940 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60548 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.03329 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63180 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.04545 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61839 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49505 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.05065 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57011 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53312 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.23652 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12323 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34195 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.12112 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20639 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.50400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03705 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.31177 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06900 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.40415 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03705 * CGRectGetHeight(frame))];
    [joyPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49505 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.75695 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03705 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24210 * CGRectGetHeight(frame))];
    [joyPath closePath];
    return joyPath;
}

+ (UIBezierPath*)emojiPrayPathForSize:(CGSize)size {
    CGRect frame = CGRectFromSize(size);
    UIBezierPath* prayPath = [UIBezierPath bezierPath];
    [prayPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.61658 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11817 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.64069 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31795 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.62416 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20142 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.62921 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28582 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.66354 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37212 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.65217 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35008 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.65861 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35229 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.69670 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54687 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.66752 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38816 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.68245 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48602 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.70653 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58221 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.70007 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56123 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.70340 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57353 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.77933 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68503 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.72296 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62764 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.77078 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67861 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.80345 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68964 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.78787 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69145 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.79581 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68842 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(500.5, 396.57) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.80931 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69058 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(470.28, 380.36)];
    [prayPath addCurveToPoint:CGPointMake(500.5, 495.5) controlPoint1:CGPointMake(500.5, 454.72) controlPoint2:CGPointMake(500.5, 495.5)];
    [prayPath addLineToPoint:CGPointMake(CGRectGetMinX(frame) + 0.66432 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99100 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.60072 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89387 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.64893 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96809 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.60849 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90771 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.58633 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84555 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.59108 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87670 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.60258 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86145 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.53226 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81274 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.58032 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83968 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.55107 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82684 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.51462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79093 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.52094 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80426 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.51629 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79077 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.49599 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81370 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.51244 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79113 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.50817 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80457 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.44130 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84856 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.47597 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82871 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.44472 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84301 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.43263 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.89401 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.43082 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86559 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.44227 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87684 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.36616 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99100 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.42486 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90785 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.38237 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96812 * CGRectGetHeight(frame))];
    [prayPath addLineToPoint:CGPointMake(CGRectGetMinX(frame) + 0.00100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99100 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.00100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81228 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.00100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99100 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.00100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91829 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.22672 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69364 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.02206 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80095 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.21949 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69480 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.25084 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68703 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.23435 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69242 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.24229 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69345 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.32363 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58221 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.25938 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68061 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.30721 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62764 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.36863 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37212 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.34005 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53678 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.36370 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39195 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.39347 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31795 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.37355 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35229 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.38199 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35008 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.41758 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11817 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.40496 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28582 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.41000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20142 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.42161 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08212 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.41878 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10497 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.42010 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09297 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.46203 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00100 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.42860 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03173 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.43966 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00620 * CGRectGetHeight(frame))];
    [prayPath addLineToPoint:CGPointMake(CGRectGetMinX(frame) + 0.48210 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00100 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.51708 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03679 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.50035 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00457 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.51239 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.01743 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.54806 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00100 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.52177 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.01743 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.52981 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00457 * CGRectGetHeight(frame))];
    [prayPath addLineToPoint:CGPointMake(CGRectGetMinX(frame) + 0.56826 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00100 * CGRectGetHeight(frame))];
    [prayPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.61658 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11817 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.59611 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00733 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.60980 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04367 * CGRectGetHeight(frame))];
    [prayPath closePath];
    return prayPath;
}

+ (UIBezierPath*)emojiRoflPathForSize:(CGSize)size {
    CGRect frame = CGRectFromSize(size);
    UIBezierPath* roflPath = [UIBezierPath bezierPath];
    [roflPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.91611 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29394 * CGRectGetHeight(frame))];
    [roflPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.99228 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36153 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.96983 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29156 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.99115 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33038 * CGRectGetHeight(frame))];
    [roflPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.95689 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42533 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.99314 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38504 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.98356 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41288 * CGRectGetHeight(frame))];
    [roflPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49400 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.96025 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44773 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47066 * CGRectGetHeight(frame))];
    [roflPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.50400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95200 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74695 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.75695 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95200 * CGRectGetHeight(frame))];
    [roflPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.21328 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84792 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.39362 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95200 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.29236 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91295 * CGRectGetHeight(frame))];
    [roflPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.13670 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84615 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.18591 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86676 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.15471 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86177 * CGRectGetHeight(frame))];
    [roflPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.12307 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74837 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.11415 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82657 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.09846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78845 * CGRectGetHeight(frame))];
    [roflPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49400 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.07439 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67561 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58812 * CGRectGetHeight(frame))];
    [roflPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.23652 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12218 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34090 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.12112 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20534 * CGRectGetHeight(frame))];
    [roflPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.50400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03600 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.31177 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06795 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.40415 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03600 * CGRectGetHeight(frame))];
    [roflPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.91611 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29394 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.68521 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03600 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.84185 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14124 * CGRectGetHeight(frame))];
    [roflPath closePath];
    return roflPath;
}

+ (UIBezierPath*)emojiBlowingKissPathForSize:(CGSize)size {
    CGRect frame = CGRectFromSize(size);
    UIBezierPath* blowingkissPath = [UIBezierPath bezierPath];
    [blowingkissPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.94200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49400 * CGRectGetHeight(frame))];
    [blowingkissPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.92500 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61805 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.94200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53699 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.93608 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57860 * CGRectGetHeight(frame))];
    [blowingkissPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.94577 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62959 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.93419 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62177 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.94153 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62627 * CGRectGetHeight(frame))];
    [blowingkissPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.96484 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74516 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.96140 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64181 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 1.00172 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67997 * CGRectGetHeight(frame))];
    [blowingkissPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.77782 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85220 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.92023 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81125 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.78989 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86057 * CGRectGetHeight(frame))];
    [blowingkissPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.77395 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84855 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.77716 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85175 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.77576 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85046 * CGRectGetHeight(frame))];
    [blowingkissPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.48400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95200 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.69499 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91320 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.59402 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95200 * CGRectGetHeight(frame))];
    [blowingkissPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.02600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49400 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.23105 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95200 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.02600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74695 * CGRectGetHeight(frame))];
    [blowingkissPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.20870 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12794 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.02600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34438 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.09774 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21152 * CGRectGetHeight(frame))];
    [blowingkissPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.48400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03600 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.28533 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.07022 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.38067 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03600 * CGRectGetHeight(frame))];
    [blowingkissPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.94200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49400 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.73695 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03600 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.94200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24105 * CGRectGetHeight(frame))];
    [blowingkissPath closePath];
    return blowingkissPath;
}

+ (UIBezierPath*)emojiStarStruckPathForSize:(CGSize)size {
    CGRect frame = CGRectFromSize(size);
    UIBezierPath* starstruckPath = [UIBezierPath bezierPath];
    [starstruckPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.75376 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08803 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.79637 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.05891 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.76849 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06566 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.78281 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.05397 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.82525 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14556 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.81611 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06609 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.82385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08906 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.89657 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23595 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.85263 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17250 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.87663 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20287 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(500.14, 142.54) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.95619 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24359 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(499.76, 128.99)];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.94167 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33665 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(500.43, 152.64) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.97755 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32135 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47200 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.95488 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37943 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42488 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.50400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93000 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72495 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.75695 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93000 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47200 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.25105 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93000 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72495 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.06613 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33731 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42512 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.05304 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37989 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.00155 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28502 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.02834 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32097 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.00155 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30271 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.10876 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24045 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.00155 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.26165 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.04809 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24533 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.17690 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15143 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.12780 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20801 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.15073 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17812 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.20649 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06000 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.17527 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10106 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.18591 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06368 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.25021 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09069 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.22040 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.05751 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.23459 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06929 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.50400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.01400 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.32285 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04224 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.41013 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.01400 * CGRectGetHeight(frame))];
    [starstruckPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.75376 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08803 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.59614 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.01400 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.68192 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04121 * CGRectGetHeight(frame))];
    [starstruckPath closePath];
    return starstruckPath;
}


+ (UIBezierPath*)emojiThinkingPathForSize:(CGSize)size {
    CGRect frame = CGRectFromSize(size);
    UIBezierPath* thinkingPath = [UIBezierPath bezierPath];
    [thinkingPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47200 * CGRectGetHeight(frame))];
    [thinkingPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.50400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93000 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72495 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.75695 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93000 * CGRectGetHeight(frame))];
    [thinkingPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.45369 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92727 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.48700 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93000 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.47021 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92907 * CGRectGetHeight(frame))];
    [thinkingPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.42732 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95255 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.44959 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93846 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.44133 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.94737 * CGRectGetHeight(frame))];
    [thinkingPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.20444 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93149 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.35382 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97974 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.23984 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97611 * CGRectGetHeight(frame))];
    [thinkingPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.17168 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78717 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.17056 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88880 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.16590 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84286 * CGRectGetHeight(frame))];
    [thinkingPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47200 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.09379 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70506 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59411 * CGRectGetHeight(frame))];
    [thinkingPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.22870 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10594 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.04600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32238 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.11774 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.18952 * CGRectGetHeight(frame))];
    [thinkingPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.50400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.01400 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.30533 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04822 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.40067 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.01400 * CGRectGetHeight(frame))];
    [thinkingPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47200 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.75695 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.01400 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.96200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21905 * CGRectGetHeight(frame))];
    [thinkingPath closePath];
    return thinkingPath;
}

+ (UIBezierPath*)emojiZipperPathForSize:(CGSize)size {
    CGRect frame = CGRectFromSize(size);
    UIBezierPath* zipperPath = [UIBezierPath bezierPath];
    [zipperPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.90442 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79189 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.84488 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83947 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.88509 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79189 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.84531 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82779 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.84531 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85972 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.84463 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84590 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.84320 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85290 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.86428 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87247 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.84703 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86528 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.85648 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87976 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.92877 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81516 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.88164 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85624 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.92141 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82369 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.92848 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80306 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.93134 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81217 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.92995 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80724 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.91705 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79344 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.92680 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79828 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.92281 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79514 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.90442 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79189 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.91348 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79239 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.90922 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79189 * CGRectGetHeight(frame))];
    [zipperPath closePath];
    [zipperPath moveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.94000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49400 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.89057 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70117 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.94000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56856 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.92218 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63896 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.98163 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81901 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.93597 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74325 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.98297 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79311 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.97713 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83294 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.98133 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82468 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.97974 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82703 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.86633 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92329 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.95829 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87546 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.88813 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92285 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.77548 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84563 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.85319 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92355 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.81432 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88779 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.48200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95200 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.69600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91204 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.59367 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95200 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.02400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49400 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.22905 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95200 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.02400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74695 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.22162 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11717 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.02400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33778 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.10221 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19983 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.48200 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03600 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.29555 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06598 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.38527 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03600 * CGRectGetHeight(frame))];
    [zipperPath addCurveToPoint:CGPointMake(CGRectGetMinX(frame) + 0.94000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49400 * CGRectGetHeight(frame)) controlPoint1:CGPointMake(CGRectGetMinX(frame) + 0.73495 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03600 * CGRectGetHeight(frame)) controlPoint2:CGPointMake(CGRectGetMinX(frame) + 0.94000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24105 * CGRectGetHeight(frame))];
    [zipperPath closePath];
    return zipperPath;
}


@end
